[project]
name = "bilitickerbuy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiofiles==23.2.1",
    "annotated-types==0.7.0",
    "anyio==4.9.0",
    "bili-ticket-gt-python==0.2.8",
    "certifi==2025.4.26",
    "charset-normalizer==3.4.2",
    "click==8.1.8",
    "colorama==0.4.6",
    "coloredlogs==15.0.1",
    "contourpy==1.3.2",
    "cycler==0.12.1",
    "decorator==5.2.1",
    "fastapi==0.115.12",
    "ffmpy==0.5.0",
    "filelock==3.18.0",
    "flatbuffers==25.2.10",
    "fonttools==4.57.0",
    "fsspec==2025.3.2",
    "gradio==4.44.1",
    "gradio-calendar==0.0.6",
    "gradio-client==1.3.0",
    "gradio-log==0.0.8",
    "greenlet==3.0.3",
    "h11==0.16.0",
    "httpcore==1.0.9",
    "httpx==0.28.1",
    "huggingface-hub==0.31.1",
    "humanfriendly==10.0",
    "idna==3.10",
    "importlib-resources==6.5.2",
    "install-playwright==0.1.0",
    "jinja2==3.1.6",
    "kiwisolver==1.4.8",
    "loguru==0.7.3",
    "markdown-it-py==3.0.0",
    "markupsafe==2.1.5",
    "matplotlib==3.10.1",
    "mdurl==0.1.2",
    "mpmath==1.3.0",
    "ntplib==0.4.0",
    "numpy==1.26.4",
    "onnxruntime==1.18.1",
    "opencv-python==4.11.0.86",
    "orjson==3.10.18",
    "packaging==25.0",
    "pandas==2.2.3",
    "pillow==10.3.0",
    "playsound3==3.2.3",
    "playwright==1.46.0",
    "protobuf==6.30.2",
    "py==1.11.0",
    "pydantic==2.8.2",
    "pydantic-core==2.20.1",
    "pydub==0.25.1",
    "pyee==11.1.0",
    "pygments==2.19.1",
    "pyparsing==3.2.3",
    "pypng==0.20220715.0",
    "pyreadline3==3.5.4",
    "python-dateutil==2.9.0.post0",
    "python-multipart==0.0.20",
    "pytz==2025.2",
    "pywin32==310",
    "pyyaml==6.0.2",
    "qrcode==7.4.2",
    "requests==2.31.0",
    "retry==0.9.2",
    "rich==14.0.0",
    "ruff==0.11.8",
    "scipy==1.15.2",
    "semantic-version==2.10.0",
    "setuptools==65.5.1",
    "shellingham==1.5.4",
    "six==1.17.0",
    "sniffio==1.3.1",
    "starlette==0.46.2",
    "sympy==1.14.0",
    "tinydb==4.8.2",
    "tomlkit==0.12.0",
    "tqdm==4.67.1",
    "typer==0.15.3",
    "typing-extensions==4.13.2",
    "tzdata==2025.2",
    "urllib3==2.4.0",
    "uvicorn==0.34.2",
    "websockets==12.0",
    "win32-setctime==1.2.0",
]
[tool.mypy]
check_untyped_defs = true

[[tool.mypy.overrides]]
module = [
    "gradio.*",
    'gradio_calendar.*',
    'scipy.*',
    'requests.*',
    'onnxruntime.*',
    'ntplib.*',
]
follow_untyped_imports = true
